### ISSUE TITLE
Intended usage of "accelerate launch"

### ISSUE THREAD

**Issue by gunshi** [UT-Austin-RPL/amago#47]
Hey,
Thanks for open-sourcing your code!
I wanted to ask whether you tested the code with accelerate in DDP mode (--mutli_gpu and --num_processes >1 ). Since the provided command in the readme doesn't use these args, on my machine I have explicitly set num_processes to be 4 for a 4 gpu experiment (accelerate errors out otherwise saying that multi_gpu requires num_processes>1).

When I do this, I get downstream errors in the code related to handling of the multiple processes (for eg. env_utils.py creates a directory for logging if it doesn't exist (in the init() of SequenceWrapper), and when running 4 instances of the code as accelerate would do, there is a clash since 4 processes try to save the directory at the exact same time). 
I did fix those errors but there are others related to client socket timeout("torch.distributed.DistNetworkError: The client socket has timed out after 600s while trying to connect to (127.0.0.1, 0).") and I wanted to post here to check before trying to debug them further.
I was wondering if you did something to avoid these errors, or whether you were testing a different setup entirely with accelerate (non-multi-gpu, or non-DDP or something else or that doesn't need >1 processes)?

Thanks!

**Comment by jakegrigsby** [comment]
Hi, yes I use accelerate for single-machine DDP internally all the time, but I quietly rewrote everything to use accelerate over the summer (long after the paper came out) and this doesn't have a ton of users outside our lab so it's definitely possible you've found a portability issue I need to fix. 

Just tested a 4-gpu setup now, here's how it should work:
![Screen Shot 2024-09-16 at 2 27 04 PM](https://github.com/user-attachments/assets/8c38c3bf-25a7-47fd-9b07-e038b2461539)


Then, let's say the regular single-gpu command is:
```bash
python 01_basic_gym.py --env Pendulum-v1 --val_interval 10  --horizon 200 --max_seq_len 32 --memory_layers 2 --run_name test_accelerate_agent --buffer_dir buffers
```

The 4-gpu accelerate version would be:
```bash
accelerate launch 01_basic_gym.py --env Pendulum-v1 --val_interval 10  --horizon 200 --max_seq_len 32 --memory_layers 2 --run_name test_accelerate_agent --buffer_dir buffers 
```

And this runs without issue for me:


![Screen Shot 2024-09-16 at 2 28 35 PM](https://github.com/user-attachments/assets/69c82140-5d6b-4ff5-ad80-2e8ad21599f6)


<img width="519" alt="Screen Shot 2024-09-16 at 3 11 14 PM" src="https://github.com/user-attachments/assets/f3d69102-fb54-4946-a5c3-d8f9dcbf7d39">


This seems to work fine using the `accelerate launch --multi-gpu --num_processes=4 ....` method too. I tried accelerate v 0.33 and 0.34

**Comment by gunshi** [comment]
Ah I see, thanks!
For others who might run into a similar issue on their cluster: I was able to get around the timeouts by specifying the exact address port to use, so my accelerate args are (for a 2 gpu expt):
accelerate launch --multi_gpu --gpu_ids "0,1" --mixed_precision bf16 --num_processes 2 --main_process_port 29500 ..<other_args>

**Comment by gunshi** [comment]
Hey! Just wanted to point out a potential issue with the data loader: since the Traj dataset is written such that its get_item doesn't actually use the input index given to it and instead samples a filename randomly, when a multi process run is launched, the seed is actually the same across processes and so all processes will sample the exact same trajectory files which nullifies the point of running multi gpu to get larger batch sizes.

**Comment by jakegrigsby** [comment]
I appreciate somebody else checking the code in this detail, thanks!

I've been looking into this. I've manually checked that the trajectory filenames loaded across accelerate processes *are* always different (across different envs, example scripts, dloader workers, and batch sizes). 

As far as I understand it, the dloader's rng syncs are handled differently than the other shared modules because they are replicated on every process. But if:
1. the lists of filenames were always in the same order across workers
2. we used `torch`'s rng to pick a filename instead of `random`
3. [we told accelerate to sync the dloader's torch random state](https://huggingface.co/docs/accelerate/v1.1.0/en/package_reference/accelerator#accelerate.Accelerator.rng_types) `Accelerator(..., rng_types=["torch"])`

*then the sampling would break exactly like you're describing*. I tested to confirm that. Luckily the `main` branch doesn't do 2 & 3, and the new version (`refactor-gc` branch) also doesn't do 1.  

Are you doing something unique with your seeding or with the accelerate config? I want to make sure this works outside all my test scripts.

**Comment by gunshi** [comment]
Hey, thanks so much for looking into this!
Sorry about the delay, I have been using this codebase with the dmlab memory-maze environment and I had thought I'd create a reproducible example using the envs from this repo before replying, but let me describe my setting here and I can post an example later if needed. 
(I'm not looking for a fix anymore as on my end I solved this already by changing the get_item() logic a little but I should rebase to the latest version of this repo soon too since I guess I'm on 2 month older version now).

One thing I'm doing differently is that I'm manually seeding in the launcher script:
So say I have a script like `examples/12_memory_maze.py`
I have the following code there:


```
    random.seed(args.expt_seed)
    torch.manual_seed(args.expt_seed)
    np.random.seed(args.expt_seed)
```
And the list of files that get picked up for the saved trajectories are indeed in the same order across processes for me, like you said. I did not do the syncing as described in your step 3 above.

Hope that helps!
